language: c

sudo: required
dist: precise

compiler: 
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmpdclient-dev cmake
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=DEBUG ..

script: make

